services:
  - type: web
    name: reminder-app
    env: dotnet
    plan: starter
    buildCommand: dotnet build --configuration Release
    startCommand: chmod +x startup.sh && ./startup.sh
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:$PORT
      - key: POSTGRES_HOST
        fromDatabase:
          name: reminder-db
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: reminder-db
          property: port
      - key: POSTGRES_DB
        fromDatabase:
          name: reminder-db
          property: database
      - key: POSTGRES_USER
        fromDatabase:
          name: reminder-db
          property: username
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: reminder-db
          property: password
      - key: APP_URL
        value: https://reminder-app.onrender.com
      - key: SMTP_SERVER
        sync: false
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: SMTP_FROM
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_FROM_PHONE
        sync: false

databases:
  - name: reminder-db
    databaseName: reminder
    user: reminder_user
    plan: starter 